layout_spectrum: 0.8924731
color:
  saturation: 0.2401434
  brandStrength: 0.1072242
  lightness: 1
  rhythmicContrast: 1
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
typography_spectrum: 0
name: N. Dybevik
